openapi: 3.0.3
info:
  title: A Simple API
  version: 1.0.0
paths:
  /simple/{someId}:
    get:
      summary: Simple get request
      operationId: getSomeStuff
      parameters:
        - in: path
          name: someId
          schema:
            type: string
            format: uuid
          required: true
          description: Some Id in the path
      responses:
        '200':
          description: OK
